REPO_URL="https://biefan.github.io/ioss/"
REPO_ORIGIN="My Jailbreak Repo"
REPO_LABEL="My Jailbreak Repo"
REPO_DESCRIPTION="Personal iOS jailbreak tweak repository"
REPO_VERSION="1.0"
REPO_SUITE="./"
REPO_CODENAME="./"
REPO_ARCHITECTURES="iphoneos-arm iphoneos-arm64"
REPO_COMPONENTS="main"
